name: .NET Core CI

on:
  push:
    branches:
      - master
      - bug/*
      - feature/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore src/AbstractBuilder.sln
    - name: Build
      run: dotnet build src/AbstractBuilder.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/AbstractBuilder.sln --no-restore --verbosity normal
