name: .NET Core CI

on:
  push:
    branches:
      - master
      - bug/*
      - feature/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Coverage
      uses: b3b00/coverlet-action@1.1.9
      with:
        testProject: 'UnitTests/UnitTests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*,[test]test.*'
        threshold: 80
