name: .NET Core CI

on:
  push:
    branches:
      - master
      - bug/*
      - feature/*
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
